# Generated by Django 4.2.7 on 2023-11-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_location_remove_shipment_weather_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='location',
        ),
        migrations.AddField(
            model_name='shipment',
            name='weather_condition',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
