# Generated by Django 4.2.7 on 2023-11-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_shipment_location_shipment_weather_condition_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_number'], name='core_shipme_trackin_8340a6_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['carrier'], name='core_shipme_carrier_1d9c3d_idx'),
        ),
    ]
