# Generated by Django 4.2.7 on 2023-11-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shipment_core_shipme_trackin_8340a6_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.shipment'),
        ),
    ]
